apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-shadcn-data-table-clone
  namespace: pluaj-dev-dev
  labels:
    app: mi-app-dt-clone
    areanegocio: tecnologia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app-dt-clone
  template:
    metadata:
      labels:
        app: mi-app-dt-clone
    spec:
      containers:
        - name: container-shadcn-data-table-clone
          image: juangrp/shadcn-data-table-clone:build-{{ tag }}   # Ajusta si subes a Docker Hub
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8082
          resources:
            requests:
              cpu: "500m"
              memory: "800Mi"
            limits:
              cpu: "1000m"
              memory: "1500Mi"
          envFrom:
            - configMapRef:
                name: mi-configmap-clone
            - secretRef:
                name: mi-secret-clone
          startupProbe:
            httpGet:
              path: /startup
              port: 8082
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8082
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: service-shadcn-data-table-clone
  namespace: pluaj-dev-dev  # Asegúrate de que coincida con tu Deployment
spec:
  selector:
    app: mi-app-dt-clone
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mi-configmap-clone
  namespace: pluaj-dev-dev
data:
  DATABASE: "192.168.1.1"
---
apiVersion: v1
kind: Secret
metadata:
  name: mi-secret-clone
  namespace: pluaj-dev-dev
type: Opaque
data:
  PASSWORD: aG9sYQ==
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route-shadcn-data-table-clone
spec:
  to:
    kind: Service
    name: service-shadcn-data-table-clone
  port:
    targetPort: http
  tls:
    termination: edge
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mi-hpa-clone
  namespace: pluaj-dev-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: deployment-shadcn-data-table-clone
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-pvc-dt-clone
  namespace: pluaj-dev-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3