apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-shadcn-data-table
  namespace: pluaj-dev-dev
  labels:
    app: mi-app-dt
    areanegocio: tecnologia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app-dt
  template:
    metadata:
      labels:
        app: mi-app-dt
    spec:
      containers:
        - name: container-shadcn-data-table
          image: juangrp/shadcn-datatable-practica:build-{{ tag }}   # Ajusta si subes a Docker Hub
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              cpu: "500m"
              memory: "800Mi"
            limits:
              cpu: "1000m"
              memory: "1500Mi"
          envFrom:
            - configMapRef:
                name: mi-configmap
            - secretRef:
                name: mi-secret
          volumeMounts:
            - name: datos
              mountPath: /app/data
      volumes:
        - name: datos
          persistentVolumeClaim:
            claimName: mi-pvc-dt
---
apiVersion: v1
kind: Service
metadata:
  name: service-shadcn-data-table
  namespace: pluaj-dev-dev  # Asegúrate de que coincida con tu Deployment
spec:
  selector:
    app: mi-app-dt
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mi-configmap
  namespace: pluaj-dev-dev
data:
  DATABASE: "192.168.1.1"
---
apiVersion: v1
kind: Secret
metadata:
  name: mi-secret
  namespace: pluaj-dev-dev
type: Opaque
data:
  PASSWORD: aG9sYQ==
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route-shadcn-data-table
spec:
  to:
    kind: Service
    name: service-shadcn-data-table
  port:
    targetPort: http
  tls:
    termination: edge
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mi-hpa
  namespace: pluaj-dev-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: deployment-shadcn-data-table
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-pvc-dt
  namespace: pluaj-dev-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3